# Generated by Django 2.2.24 on 2021-12-05 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11)),
                ('password', models.CharField(max_length=80)),
                ('face', models.CharField(max_length=100)),
                ('nikename', models.CharField(max_length=20, null=True)),
                ('homeaddress', models.CharField(max_length=100, null=True)),
                ('sex', models.CharField(max_length=1, null=True)),
                ('usertype', models.CharField(max_length=50)),
            ],
        ),
    ]
