# Generated by Django 2.2.24 on 2021-12-09 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0002_booktype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bkname', models.CharField(max_length=40)),
                ('bkreco', models.CharField(max_length=50)),
                ('bkbrief', models.CharField(max_length=100)),
                ('bkauthor', models.CharField(max_length=30)),
                ('bkpress', models.CharField(max_length=40)),
                ('bktime', models.DateField()),
                ('bkprice', models.FloatField()),
                ('bktypeid', models.ManyToManyField(to='myadmin.BookType')),
            ],
        ),
        migrations.CreateModel(
            name='BooksImgs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgurl', models.ImageField(upload_to='myadmin/images/book')),
                ('imgbkid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.Books')),
            ],
        ),
    ]
