# Generated by Django 2.2.24 on 2021-12-10 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0003_books_booksimgs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booksimgs',
            name='imgurl',
            field=models.ImageField(upload_to='myadmin/images/book/'),
        ),
    ]
