# Generated by Django 2.2.24 on 2021-12-10 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0004_auto_20211210_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booksimgs',
            name='imgurl',
            field=models.ImageField(upload_to='static/myadmin/images/book/'),
        ),
    ]
