# Generated by Django 2.2.24 on 2021-12-11 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0005_auto_20211210_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='bkbrief',
            field=models.CharField(max_length=300),
        ),
    ]
