# Generated by Django 2.2.24 on 2021-12-15 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0006_auto_20211211_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='face',
            field=models.CharField(default='/static/myadmin/images/face/default_face.jpg', max_length=100),
        ),
    ]
