# Generated by Django 2.2.24 on 2021-12-15 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0007_auto_20211215_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='bkbrief',
            field=models.CharField(max_length=500),
        ),
    ]
